import { paletteCss, tokenClassName } from "@/lib/code/palette";

/**
 * Moves a markdown code fence's token colours out of an inline `style` into a class, the way
 * PF-009 did for the code viewer (PF-015).
 *
 * **PF-009 named this as the piece it left behind**, because a fence's HTML is generated by
 * `rehypeShikiFromHighlighter` and never passes through `CodeLine`. Measured on a 42-line Python
 * fence in an exercise text: **239 inline `--shiki-light` declarations, 11,996 bytes of a 113,797-
 * byte document**, and not one palette class. The same 239 spans carry about 4.8 kB of class
 * attributes instead, plus a few hundred bytes of rules -- around 7 kB off a page every student in
 * the course opens.
 *
 * Written as a plain recursive walk rather than with `unist-util-visit`, which is not a dependency
 * of this repo: it arrives under react-markdown, and importing it directly would be a phantom
 * dependency that pnpm's strict layout is there to catch.
 *
 * The rules go in a `<style>` beside each `<pre>` rather than in one block for the document,
 * because a fence is rendered wherever the author put it and there is no document-level slot to
 * reach from inside a plugin. Duplicate rules across two fences are identical by construction --
 * the class name is derived from the colours (see `palette.ts`) -- so the cost of repeating one is
 * a few bytes and the alternative is plumbing state out of the tree.
 */
interface HastNode {
  type: string;
  tagName?: string;
  properties?: Record<string, unknown>;
  children?: HastNode[];
  value?: string;
}

/** `--shiki-light:#005CC5;--shiki-dark:#79B8FF` as Shiki writes it, in either order. */
function readShikiStyle(style: string): Record<string, string> | null {
  const light = /--shiki-light:\s*([^;]+)/.exec(style)?.[1]?.trim();
  const dark = /--shiki-dark:\s*([^;]+)/.exec(style)?.[1]?.trim();
  if (light === undefined || dark === undefined) return null;
  return { "--shiki-light": light, "--shiki-dark": dark };
}

/**
 * Adds a class without disturbing the ones already there.
 *
 * **`class` as well as `className`**, because the two are not interchangeable here:
 * `@shikijs/rehype` writes `properties.class` while hast's canonical key is `className`, and
 * react-markdown honours `className` and ignores `class` once both exist. Writing only `className`
 * therefore *replaced* the `<pre class="shiki">` marker rather than adding to it -- which two specs
 * caught, because `.shiki` is what the styling and those assertions both key on.
 */
function addClass(properties: Record<string, unknown>, name: string): void {
  const key =
    "className" in properties ? "className" : "class" in properties ? "class" : "className";
  const existing = properties[key];
  properties[key] = Array.isArray(existing)
    ? [...existing, name]
    : typeof existing === "string" && existing !== ""
      ? `${existing} ${name}`
      : name;
}

function classify(node: HastNode, palette: Record<string, string>[]): void {
  const style = node.properties?.style;
  if (typeof style === "string") {
    const parsed = readShikiStyle(style);
    const name = parsed === null ? "" : tokenClassName(parsed);
    // A style this palette cannot express keeps its inline copy, which is `tokenClassName`'s own
    // escape hatch: a future theme emitting anything but a plain hex colour degrades rather than
    // writing something unintended into a stylesheet.
    if (parsed !== null && name !== "") {
      palette.push(parsed);
      delete node.properties!.style;
      addClass(node.properties!, name);
    }
  }
  for (const child of node.children ?? []) classify(child, palette);
}

export function rehypeShikiPalette() {
  return (tree: HastNode): void => {
    const stack: HastNode[] = [tree];
    while (stack.length > 0) {
      const node = stack.pop()!;
      for (const child of node.children ?? []) {
        if (child.tagName === "pre") {
          const palette: Record<string, string>[] = [];
          // The `<pre>`'s own `--shiki-*` pair is the block's background, not a token, and it is
          // one attribute against the hundreds inside -- so it is left inline. Turning it into a
          // token class would also file the background under a name meaning "a token of these
          // colours", which is a collision waiting to mean the wrong thing.
          for (const inner of child.children ?? []) classify(inner, palette);
          const css = paletteCss(palette);
          if (css !== "") {
            child.children = [
              {
                type: "element",
                tagName: "style",
                properties: {},
                children: [{ type: "text", value: css }],
              },
              ...(child.children ?? []),
            ];
          }
          continue;
        }
        stack.push(child);
      }
    }
  };
}
